/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "stm32f103c6_gpio_driver.h"
#include "lcd.h"
#include "keypad.h"
#include "stm32f103c6_exti_driver.h"
uint8 IRQ_Flag = 0;
void my_wait(int x)
{
	int i,j;
	for(i=0;i<x;i++)
	{
		for(j=0;j<255;j++);
	}
}
void EXTI9_Callback(void)
{
	IRQ_Flag = 1;
	LCD_WRITE_STRING("IRQ EXTI9 IS HAPPENED");
	my_wait(1000);
}
int main(void)
{
	RCC_GPIOA_CLOCK_EN();
	RCC_GPIOB_CLOCK_EN();
	RCC_AFIO_CLOCK_EN();
	LCD_INIT();
	LCD_clear_screen();
	Dt_exti_config exti_cfg;
	exti_cfg.exti_mapping = EXTI9PB9;
	exti_cfg.trigger_condition = EXTI_TRIGGER_RISING;
	exti_cfg.p_irq_callback = EXTI9_Callback;
	exti_cfg.irq_enable = EXTI_IRQ_ENABLE;
	MCAL_exti_gpio_init(&exti_cfg);
	while(1)
	{
		if(IRQ_Flag)
		{
			LCD_clear_screen();
			IRQ_Flag =0;
		}
		my_wait(1000);
	}
}
